stages:
  preprocess-p:
    cmd: python src/preprocess.py -d data/raw/data.csv -o data/preprocessed/data.csv
  train:
    cmd: python src/train.py
    deps:
      - data/raw/data.csv
      - src/train.py
    params:
      - train.data
      - train.max_depth
      - train.model
      - train.n_estimators
      - train.random_state
    outs:
      - models/model.pkl
  evaluate:
    cmd: python src/evaluate.py
    deps:
      - data/raw/data.csv
      - models/model.pkl
      - src/evaluate.py
